apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: my-web
spec:
  replicas: 1          # 평소에는 1개만 띄움 (비용 절약)
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        # ★ 이미지 주소 수정 (본인 NCR 주소 + 태그)
        image: my-repo.kr.ncr.ntruss.com/my-web-app:8 
        ports:
        - containerPort: 80
        # ★ [중요] 오토 스케일링을 위한 CPU 기준점 설정
        resources:
          requests:
            cpu: "100m"  # 0.1 코어 (기준)
          limits:
            cpu: "200m"  # 0.2 코어 (최대)
      imagePullSecrets:
      - name: ncr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  namespace: my-web
spec:
  type: ClusterIP
  selector:
    app: my-web-app
  ports:
  - port: 80
    targetPort: 80
---
# ★ 오토 스케일러 (HPA) 추가
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-hpa
  namespace: my-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-app
  minReplicas: 1    # 최소 1개
  maxReplicas: 10   # 최대 10개까지 늘려라!
  targetCPUUtilizationPercentage: 50 # CPU 사용률 50% 넘으면 스케일 아웃!
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-ingress
  namespace: my-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-web-service
            port:
              number: 80
